ourapp/urls.py
from django.conf.urls import url
from ourapp import views

#Template URLS
app_name = 'ourapp'

urlpatterns=[
url(r'^register/$',views.register,name='register'),
url(r'^user_login/$',views.user_login,name='user_login')
]

oursite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from ourapp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^ourapp/',include('ourapp.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special')
]

ourapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional information that you want to add to your signup page
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

ourapp/forms.py
from django import forms
from django.contrib.auth.models import User
from ourapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

ourapp/views.py
from django.shortcuts import render
from ourapp.forms import UserForm,UserProfileInfoForm
# Create your views here.
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request,'ourapp/index.html')

@login_required
def special(request):
    return HttpResponse("You Are Successfully Loged In!")

#So it is going to make sure that the one which is not logged in at the moment will not looged out
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()

            #password
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'ourapp/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not Active")
        else:
            print("Some One Try To Login And Failed!")
            print("Username: {} And Password: {}".format(username,password))
            return HttpResponse("Invalid Login Details Supplied!")
    else:
        return render(request,'ourapp/login.html',{})

templates/ourapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="http://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg " style=" background: -webkit-gradient(radial, center center, 0, center center, 460, from(#1a82f7), to(#2F2727));

  /* Safari 5.1+, Chrome 10+ */
    background: -webkit-radial-gradient(circle, #1a82f7, #2F2727);

  /* Firefox 3.6+ */
    background: -moz-radial-gradient(circle, #1a82f7, #2F2727);

  /* IE 10 */
    background: -ms-radial-gradient(circle, #1a82f7, #2F2727);
    height:100px;">
    <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
        <ul class="nav navbar-nav ">
          <!--<li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>-->
          <li class="nav-item mx-4px"><a class="navbar-link " href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item mx-4px"><a class="navbar-link " href="{% url 'ourapp:register'%}">Registration</a></li>


          {% if user.is_authenticated %}
          <li class="nav-item mx-4px"><a class="navbar-link " href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item mx-4px"><a class="navbar-link " href="{% url 'ourapp:user_login'%}">Login</a></li>
          {% endif %}
        </ul>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

templates/ourapp/index.html
{% extends "ourapp/base.html" %}
{% block body_block %}
<!--navbar edition is still left-->
<div class="jumbotron">
  <h1>Django</h1>
</div>
{% endblock %}

templates/ourapp/login.html
{% extends "ourapp/base.html" %}

{% block body_block %}
<!--it is going to visit the the ourapp and user_login in views.py-->
  <h1 class="my-4">LOGIN</h1>
  <form action="{% url 'ourapp:user_login' %}" method="post" class="my-4">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>
{% endblock %}

templates/ourapp/registration.html
{% extends 'ourapp/base.html' %}



{% block body_block %}
  {% if registered %}
  <h1 class="my-4">kam karna hai isme abhi</h1>
  {% else %}
  <h1 class="my-4">register not complete</h1>


  <form enctype="multipart/form-data" method="post" class="my-4">
    {% csrf_token %}
    <!--gathering info from form-->
    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <input type="submit" name="" value="Register">
  </form>
  {% endif %}
{% endblock %}